state.online=false;state.seat=0;state.host=false;state.room='';state.drops=[0,0];state.scoreAck=[false,false];state.peerGone=false;state.netMode='local';
var net={peer:null,conn:null,syncing:false};
function roomCode(){var a='23456789ABCDEFGHJKLMNPQRSTUVWXYZ',s='';for(var i=0;i<4;i++)s+=a[Math.floor(Math.random()*a.length)];return s;}
function peerId(code){return 'hsp16-'+String(code).toUpperCase();}
function packState(){return{nick:state.nick,totalRounds:state.totalRounds,round:state.round,starter:state.starter,turn:state.turn,wins:state.wins,penalty:state.penalty,alive:state.alive,phase:state.phase,dice:state.dice,selDie:state.selDie,selDie2:state.selDie2,selOp:state.selOp,blink:state.blink,jokers:state.jokers,jMode:state.jMode,jLocked:state.jLocked,jPick:state.jPick,chain:state.chain,timeLeft:state.timeLeft,turnSec:state.turnSec,screen:state.screen,scoreKind:state.scoreKind,scoreWinner:state.scoreWinner,scoreLast:state.scoreLast,scoreFinal:state.scoreFinal,scorePes:state.scorePes,scoreAck:state.scoreAck,drops:state.drops,reply:state.reply,finishedThisTurn:state.finishedThisTurn};}
function applyPack(p){if(!p)return;net.syncing=true;['nick','totalRounds','round','starter','turn','wins','penalty','alive','phase','dice','selDie','selDie2','selOp','blink','jokers','jMode','jLocked','jPick','chain','timeLeft','turnSec','screen','scoreKind','scoreWinner','scoreLast','scoreFinal','scorePes','scoreAck','drops','reply','finishedThisTurn'].forEach(function(k){if(p[k]!==undefined)state[k]=p[k];});if(state.screen==='score'||state.screen==='result')scoreView();else if(state.screen==='play')render();else if(state.screen==='home')home();net.syncing=false;}
function send(msg){if(net.conn&&net.conn.open){try{net.conn.send(msg);}catch(e){}}}
function hostPush(){if(state.online&&state.host)send({t:'snap',p:packState()});}
function closeNet(){try{if(net.conn)net.conn.close();}catch(e){}try{if(net.peer)net.peer.destroy();}catch(e){}net.peer=net.conn=null;state.online=false;state.host=false;state.peerGone=false;}
function onPeerLost(){if(!state.online)return;var other=1-state.seat;state.peerGone=true;if(state.screen==='score'||state.screen==='result'){state.drops[other]+=1;if(state.drops[other]>=3){if(typeof showResult==='function')showResult('pes',state.seat,other);else{state.scoreKind='pes';state.scorePes=other;state.scoreFinal=true;state.screen='score';scoreView();}}else if(typeof scoreView==='function')scoreView();return;}if(state.turn!==other)return;state.drops[other]+=1;if(state.drops[other]>=3){if(typeof showResult==='function')showResult('pes',state.seat,other);else{state.scoreKind='pes';state.scorePes=other;state.scoreFinal=true;state.screen='score';scoreView();}hostPush();return;}if(state.phase==='needRoll'||state.phase==='choose'||state.phase==='pickJoker'){if(typeof startClock==='function'&&!state.timeIv)startClock();}}
function wireConn(c){net.conn=c;c.on('data',function(msg){if(!msg||!msg.t)return;if(msg.t==='hello'&&state.host){state.nick[1]=String(msg.nick||'Rakip').slice(0,14);send({t:'welcome',nick:state.nick[0],turnSec:state.turnSec,totalRounds:state.totalRounds});state.online=true;state.seat=0;state.drops=[0,0];startGame();hostPush();return;}if(msg.t==='welcome'&&!state.host){state.nick[0]=msg.nick;if(msg.turnSec)state.turnSec=msg.turnSec;if(msg.totalRounds)state.totalRounds=msg.totalRounds;return;}if(msg.t==='snap'&&!state.host)applyPack(msg.p);if(msg.t==='cmd'&&state.host)runCmd(msg.c);if(msg.t==='ack'){state.scoreAck[msg.s]=true;if(state.host)hostPush();if(state.scoreAck[0]&&state.scoreAck[1])finishScoreAcks();else if(typeof scoreView==='function')scoreView();}});c.on('close',onPeerLost);c.on('error',onPeerLost);}
function runCmd(c){if(!c||net.syncing)return;if(c.a==='roll'&&typeof rollDice==='function')rollDice();if(c.a==='die'&&typeof pickSource==='function')pickSource({t:'d',i:c.i,p:state.turn});if(c.a==='j'&&typeof pickSource==='function')pickSource({t:'j',i:c.i,p:state.turn});if(c.a==='op'){var last=state.chain[state.chain.length-1];if(typeof last==='string')state.chain[state.chain.length-1]=c.op;else if(state.chain.length===1||(state.jMode&&state.chain.length===3))state.chain.push(c.op);state.selOp=c.op;render();}if(c.a==='jmode'){if(state.jokers[state.turn]&&state.jokers[state.turn].length&&!state.jLocked){state.jMode=!state.jMode;state.chain=[];clearSel();render();}}if(c.a==='jpick'){if(state.phase==='pickJoker'&&state.jokers[state.turn].length<2){state.jokers[state.turn].push(c.n);state.jPick=false;state.phase='choose';if(typeof stopClock==='function')stopClock();render();if(typeof startClock==='function')startClock();}}if(c.a==='pass'){state.jPick=false;state.jMode=false;state.jLocked=false;state.chain=[];clearSel();state.finishedThisTurn=false;afterPlay();}if(c.a==='pes'&&typeof showResult==='function')showResult('pes',1-c.p,c.p);hostPush();}
var _homeNet=home;
home=function(){_homeNet();var v=document.querySelector('.ver');if(v)v.textContent='V16';var go=document.getElementById('go');if(!go||document.getElementById('netrow'))return;var row=document.createElement('div');row.id='netrow';row.className='netrow';row.innerHTML='<button type="button" class="netbtn" id="btnlocal">Yerel</button><button type="button" class="netbtn" id="btnhost">Oda kur</button><button type="button" class="netbtn" id="btnjoin">Odaya gir</button>';go.parentNode.insertBefore(row,go);document.getElementById('btnlocal').onclick=function(){state.netMode='local';state.online=false;go.click();};document.getElementById('btnhost').onclick=function(){var n=(document.getElementById('n0')||{}).value||state.nick[0];if(!String(n).trim()){alert('Nick yaz');return;}state.nick[0]=String(n).trim();var s=document.getElementById('secs');if(s)state.turnSec=parseInt(s.value,10)||10;var r=document.getElementById('rounds');if(r)state.totalRounds=parseInt(r.value,10)||4;openHost();};document.getElementById('btnjoin').onclick=function(){openJoin();};go.textContent='YEREL BASLAT';};
function waitHtml(title,body){app.innerHTML='<div class="home waitbox"><h1>HESAPLA</h1>'+body+'<button type="button" class="start" id="netback">Geri</button><div class="ver">V16</div></div>';document.getElementById('netback').onclick=function(){closeNet();home();};}
function openHost(){state.host=true;state.online=true;state.seat=0;state.room=roomCode();waitHtml('Oda','<p class="waitlab">Oda kodu</p><div class="roomcode" id="rcode">'+state.room+'</div><button type="button" class="start copybtn" id="copyc">Kopyala</button><p class="waitlab">Rakip bekleniyor</p>');document.getElementById('copyc').onclick=function(){var t=state.room;if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(t);else{var i=document.createElement('input');i.value=t;document.body.appendChild(i);i.select();try{document.execCommand('copy');}catch(e){}document.body.removeChild(i);}this.textContent='Kopyalandi';};if(typeof Peer==='undefined'){alert('Baglanti kutuphanesi yok');return;}net.peer=new Peer(peerId(state.room));net.peer.on('connection',function(c){wireConn(c);});net.peer.on('error',function(){alert('Oda acilamadi');closeNet();home();});}
function openJoin(){waitHtml('Gir','<label>Nick</label><input id="jn" maxlength="14" placeholder="Nick" /><label>Oda kodu</label><input id="jc" maxlength="6" placeholder="KOD" style="text-transform:uppercase" /><button type="button" class="start" id="jgo">Baglan</button>');document.getElementById('jgo').onclick=function(){var nick=(document.getElementById('jn').value||'').trim();var code=(document.getElementById('jc').value||'').trim().toUpperCase();if(!nick||code.length<4){alert('Nick ve kod');return;}state.nick[1]=nick;state.seat=1;state.host=false;state.online=true;state.room=code;if(typeof Peer==='undefined'){alert('Baglanti yok');return;}net.peer=new Peer();net.peer.on('open',function(){var c=net.peer.connect(peerId(code),{reliable:true});c.on('open',function(){wireConn(c);send({t:'hello',nick:nick});});c.on('error',function(){alert('Oda bulunamadi');closeNet();home();});});net.peer.on('error',function(){alert('Baglanamadi');closeNet();home();});};}
var _bindNet=bindTable;
bindTable=function(){_bindNet();if(!state.online)return;if(state.seat===1){var t=app.querySelector('.table');if(t){var top=t.querySelector('.half.top');var bot=t.querySelector('.half.bot');if(top&&bot){top.classList.remove('top');top.classList.add('bot');bot.classList.remove('bot');bot.classList.add('top');t.insertBefore(bot,t.firstChild);t.appendChild(top);}}}if(state.host){setTimeout(hostPush,30);return;}app.querySelectorAll('.zar').forEach(function(b){b.onclick=function(e){e.preventDefault();if(state.turn!==state.seat)return;send({t:'cmd',c:{a:'roll'}});};});app.querySelectorAll('.die-wrap').forEach(function(el){el.onclick=function(){if(state.turn!==state.seat||state.phase!=='choose')return;send({t:'cmd',c:{a:'die',i:parseInt(el.dataset.die,10)}});};});app.querySelectorAll('.op').forEach(function(el){el.onclick=function(){if(state.turn!==state.seat||state.phase!=='choose')return;send({t:'cmd',c:{a:'op',op:el.dataset.op}});};});app.querySelectorAll('.midkit .jbtn').forEach(function(b){b.onclick=function(e){e.preventDefault();e.stopPropagation();if(state.turn!==state.seat)return;send({t:'cmd',c:{a:'jmode'}});};});app.querySelectorAll('.jpick-float .mdie.pickable').forEach(function(el){el.onclick=function(e){e.stopPropagation();if(state.turn!==state.seat)return;send({t:'cmd',c:{a:'jpick',n:parseInt(el.dataset.jv,10)}});};});app.querySelectorAll('.midkit .mdie.owned').forEach(function(el){el.onclick=function(e){e.stopPropagation();if(state.turn!==state.seat)return;send({t:'cmd',c:{a:'j',i:parseInt(el.getAttribute('data-ji'),10)}});};});app.querySelectorAll('.midkit .turn-dot.holdable').forEach(function(dot){var hold=null;function cancel(){if(hold){clearTimeout(hold);hold=null;}dot.classList.remove('holding');}dot.onpointerdown=function(e){e.preventDefault();e.stopPropagation();if(state.turn!==state.seat)return;if(state.phase!=='choose'&&state.phase!=='pickJoker')return;dot.classList.add('holding');hold=setTimeout(function(){hold=null;send({t:'cmd',c:{a:'pass'}});},500);};dot.onpointerup=dot.onpointerleave=dot.onpointercancel=cancel;});};
var _rollNet=rollDice;
rollDice=function(){if(state.online&&!state.host&&!net.syncing){send({t:'cmd',c:{a:'roll'}});return;}_rollNet();if(state.online&&state.host){var iv=setInterval(function(){hostPush();if(state.phase!=='rolling')clearInterval(iv);},120);}};
if(typeof paintClock==='function'){var _paintNet=paintClock;paintClock=function(){_paintNet();if(state.online&&state.host)hostPush();};}
var _afterNet=afterPlay;
afterPlay=function(){_afterNet();if(state.online&&state.host)hostPush();};
var _scoreGo=onScoreGo;
onScoreGo=function(){if(!state.online){_scoreGo();return;}state.scoreAck=state.scoreAck||[false,false];state.scoreAck[state.seat]=true;send({t:'ack',s:state.seat});if(state.scoreAck[0]&&state.scoreAck[1])finishScoreAcks();else scoreView();};
function finishScoreAcks(){state.scoreAck=[false,false];_scoreGo();if(state.online&&state.host)hostPush();}
var _scoreView=scoreView;
scoreView=function(){var me=state.online?state.seat:0;var opp=1-me;var ack=(state.scoreAck&&state.scoreAck[me])?'Onaylandi':scoreBtnLabel();function card(p,cls){var o=1-p;var h='<div class="score-half '+cls+'"><div class="score-card">';h+='<h2>'+esc(scoreTitle())+'</h2>';h+='<div class="score-me"><b>'+esc(state.nick[p])+'</b><span>Tur '+state.wins[p]+'</span><span>Ceza '+state.penalty[p]+'</span></div>';h+='<div class="score-op"><b>'+esc(state.nick[o])+'</b><span>Tur '+state.wins[o]+'</span><span>Ceza '+state.penalty[o]+'</span></div>';if(state.online&&state.scoreAck&&state.scoreAck[o])h+='<p class="waitlab">Rakip onayladi</p>';h+='<button type="button" class="score-go">'+ack+'</button></div></div>';return h;}app.innerHTML='<div class="score">'+card(opp,'top')+card(me,'bot')+'<div class="ver">V16</div></div>';app.querySelectorAll('.score-go').forEach(function(b){b.onclick=onScoreGo;});};
if(state.screen==='home')home();
